/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.RegistroVehiculos;

/**
 *
 * @author labinf
 */
public class FrmMain extends javax.swing.JFrame {

    FrmAccion1 a1;
    FrmAccion2 a2;

        public FrmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        initGUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desk1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuAccion1 = new javax.swing.JMenuItem();
        mnuAccion2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desk1Layout = new javax.swing.GroupLayout(desk1);
        desk1.setLayout(desk1Layout);
        desk1Layout.setHorizontalGroup(
            desk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desk1Layout.setVerticalGroup(
            desk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuFile.setMnemonic('A');
        mnuFile.setText("Archivo");

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/cerrar-sesion.png"))); // NOI18N
        mnuSalir.setMnemonic('S');
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSalir);

        jMenuBar1.add(mnuFile);

        mnuEdit.setText("Acciones");

        mnuAccion1.setText("Vehiculos");
        mnuAccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAccion1ActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuAccion1);

        mnuAccion2.setText("Acción 2");
        mnuAccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAccion2ActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuAccion2);

        jMenuBar1.add(mnuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuAccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAccion1ActionPerformed
        hideFrames();
        a1.setSize(desk1.getSize());
        a1.setVisible(true);
        a1.show();

    }//GEN-LAST:event_mnuAccion1ActionPerformed

    private void mnuAccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAccion2ActionPerformed
        hideFrames();
        a2.setVisible(true);
        a2.show();
    }//GEN-LAST:event_mnuAccion2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desk1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAccion1;
    private javax.swing.JMenuItem mnuAccion2;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables

    private void initGUI() {
        a1 = new FrmAccion1();
        a2 = new FrmAccion2();

        a1.setSize(desk1.getSize());
        a2.setSize(desk1.getSize());

        desk1.add(a1);
        desk1.add(a2);

        a1.pack();
        a1.setUI(null);

        a2.pack();
        a2.setUI(null);

    }

    private void hideFrames() {
        a1.setVisible(false);
        a2.setVisible(false);
    }
}
