/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javafx.scene.control.ToggleButton;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author labinf
 */
public class FrmOpciones extends javax.swing.JFrame {

    /**
     * Creates new form FrmOpciones
     */
    public FrmOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCarreras = new javax.swing.ButtonGroup();
        cboDias = new javax.swing.JComboBox<>();
        btnCombo = new javax.swing.JButton();
        lblDias = new javax.swing.JLabel();
        chkMañana = new javax.swing.JCheckBox();
        chkTarde = new javax.swing.JCheckBox();
        btnCheck = new javax.swing.JButton();
        optIngeniería = new javax.swing.JRadioButton();
        optTécnico = new javax.swing.JRadioButton();
        btnRadio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        cboDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiasActionPerformed(evt);
            }
        });

        btnCombo.setText("Aceptar");
        btnCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComboActionPerformed(evt);
            }
        });

        chkMañana.setText("Mañana");
        chkMañana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMañanaActionPerformed(evt);
            }
        });

        chkTarde.setText("Tarde");

        btnCheck.setText("Aceptar");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        grupoCarreras.add(optIngeniería);
        optIngeniería.setText("Ingeniería en Informática");

        grupoCarreras.add(optTécnico);
        optTécnico.setText("TU en Informática");

        btnRadio.setText("Aceptar");
        btnRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optIngeniería)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optTécnico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRadio))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCombo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(chkMañana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkTarde)
                                .addGap(22, 22, 22)
                                .addComponent(btnCheck)))
                        .addGap(31, 31, 31)
                        .addComponent(lblDias, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCombo))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkMañana)
                            .addComponent(chkTarde)
                            .addComponent(btnCheck))))
                .addGap(41, 41, 41)
                .addComponent(optIngeniería)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optTécnico)
                    .addComponent(btnRadio))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComboActionPerformed
        int index = cboDias.getSelectedIndex();
        String dia = cboDias.getSelectedItem().toString();

        if (index == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debes seleccionar un día",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {

            JOptionPane.showMessageDialog(rootPane,
                    "Seleccionado día " + dia,
                    "Index " + index,
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnComboActionPerformed

    private void cboDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiasActionPerformed
        String dia = cboDias.getSelectedItem().toString();
        lblDias.setText(dia);
    }//GEN-LAST:event_cboDiasActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        String dia = cboDias.getSelectedItem().toString();
        String cita = "";
        if (chkMañana.isSelected()) {
            cita += dia + " en la mañana\n";
        }
        if (chkTarde.isSelected()) {
            cita += dia + " en la tarde\n";
        }
        lblDias.setText(cita);
    }//GEN-LAST:event_btnCheckActionPerformed

    private void chkMañanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMañanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMañanaActionPerformed

    private void btnRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioActionPerformed
        String carrera = "";
        if (optIngeniería.isSelected()) {
            carrera = "Igeniería en Informática";
        }
        if (optTécnico.isSelected()) {
            carrera = "TU en Informática";
        }
        JOptionPane.showMessageDialog(rootPane, carrera);
        
        
    }//GEN-LAST:event_btnRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnCombo;
    private javax.swing.JButton btnRadio;
    private javax.swing.JComboBox<String> cboDias;
    private javax.swing.JCheckBox chkMañana;
    private javax.swing.JCheckBox chkTarde;
    private javax.swing.ButtonGroup grupoCarreras;
    private javax.swing.JLabel lblDias;
    private javax.swing.JRadioButton optIngeniería;
    private javax.swing.JRadioButton optTécnico;
    // End of variables declaration//GEN-END:variables
}
